### ISSUE TITLE
卡在“Start success on port 65432”无响应，请求帮助

### ISSUE THREAD

**Issue by real-Shigure** [Nick-Hopps/v2-ui-plus#7]
系统：Debian 10
环境：已安装python3及其所需的包；已使用root权限；已打开必要端口

错误描述：在使用python3 v2-ui.py指令进行启动后，程序便会卡在“Start success on port 65432”而没有下一步响应，同时面板也无法访问

=>在卡住时按下ctrl c后输出的信息：
2021-03-10 08:54:02 root[ERROR]:
Traceback (most recent call last):
  File "v2-ui.py", line 79, in <module>
    raise e
  File "v2-ui.py", line 76, in <module>
    main()
  File "v2-ui.py", line 40, in main
    IOLoop.current().start()
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/usr/local/python3/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/usr/local/python3/lib/python3.7/asyncio/base_events.py", line 1735, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/python3/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)

不知道在哪可能出现了错误？本人小白一只，期待大佬的回复，谢谢！！

**Comment by real-Shigure** [comment]
> 显示 “Start success on port 65432” 就是启动成功了，之后去浏览器访问就行了，会用 docker 的话用我给的 dockerfile 编译，否则用 screen 保持后台运行也行。

不过访问面板（xx.xx.xx.xx:65432）显示超时  ERR_CONNECTION_TIMED_OUT，不太明白有可能是哪里出了问题？（如果显示Start success的话应该可以正确访问才对。我先重新安装一遍试试），谢谢啦

**Comment by real-Shigure** [comment]
看了一下65432端口倒是打开了

**Comment by Nick-Hopps** [comment]
如果确认端口开了还访问不了，那有可能是防火墙的问题。



---原始邮件---
发件人: "real-Shigure"<notifications@github.com&gt;
发送时间: 2021年3月11日(周四) 凌晨0:08
收件人: "Nick-Hopps/v2-ui-plus"<v2-ui-plus@noreply.github.com&gt;;
抄送: "Nick_Hopps"<nickhopps@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [Nick-Hopps/v2-ui-plus] 卡在“Start success on port 65432”无响应，请求帮助 (#7)




 
看了一下65432端口倒是打开了
